<a href="https://colab.research.google.com/github/ArtyomShabunin/SMOPA/blob/main/lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Занятие №1
# Python и библиотеки для анализа данных и математического моделирования

## Установка Python

![anaconda image](https://www.anaconda.com/wp-content/uploads/2022/12/anaconda_secondary_logo.svg)

**Anaconda** — дистрибутив языков программирования Python и R, включающий набор популярных свободных библиотек, объединённых проблематиками науки о данных и машинного обучения. Основная цель — поставка единым согласованным комплектом наиболее востребованных соответствующим кругом пользователей тематических модулей (таких как NumPy, SciPy, Astropy и других) с разрешением возникающих зависимостей и конфликтов, которые неизбежны при одиночной установке.

Программа Anaсonda представляет собой полноценную систему работы с библиотеками Python, включающую программу-установщик и набор следующих файлов.

* **Библиотеки.** Каждая из них включает определенный набор функций и объектов, предназначенный для решения конкретных задач — например, работы с массивами данных, астрономических вычислений, обработки изображений, построения и тренировки нейронных сетей, различных инженерных расчетов, статистического анализа и т.д. Всего в пакет Anaconda входит около 1500 библиотек, объединенных научной и инженерной тематикой.
* **Менеджер пакетов Conda.** Это кроссплатформенное программное обеспечение, предназначенное для установки пакетов ПО и библиотек, быстрого переключения между их версиями, загрузки и инсталляции обновлений. Conda написана на Python, но является языково-независимой, то есть может работать с проектами, написанными на любом языке программирования. Кроме того, с ее помощью можно установить и сам Python — возможность, предусмотренная далеко не во всех менеджерах пакетов, написанных на этом ЯП. Из-за того, что менеджер пакетов оказался очень удобен для решения задач, не связанных с Python, он был выделен в отдельный дистрибутив с открытым исходным кодом.
* **Менеджер виртуальной среды.** Это программа, позволяющая создавать, редактировать, удалять и отслеживать состояние виртуальных машин. Управление изолированными виртуальными средами осуществляется из единой контрольной консоли. Виртуализация используется при работе над несколькими проектами одновременно, позволяя исключить их влияние друг на друга, тем самым обеспечив высокую точность расчетов.
* **GIU Anaconda Navigator.** GUI (graphic user interface) — графический интерфейс пользователя, то есть программная оболочка, в которой можно работать с библиотеками не с помощью текстовых команд, а используя визуальные элементы, такие как блоки, модули, графики и т.д. «Анаконда Навигатор» существенно упрощает взаимодействие с библиотеками, делает работу менее однообразной и утомительной, повышает наглядность рабочего процесса.

https://www.anaconda.com/

### Установка виртуального окружения
С помощью виртуального окружения можно создать изолированный контейнер с нужными версиями под каждую задачу.  
```conda env create -f environment.yml```  
```conda activate mpei```

## Инструмент разработки

![jupyter image](https://jupyter.org/assets/logos/rectanglelogo-greytext-orangebody-greymoons.svg)

**Jupyter Notebok** — браузерный инструмент для оформления красивой и информативной аналитики, совместного хранения кода, картинок, примечаний, диаграмм, формул и т.д.

В мире Data Science Jupyter-ноутбук уже несколько лет считается одним из популярных инструментов для анализа данных и быстрого прототипирования.

Один из плюсов этого инструмента в том, что код можно разделить на кусочки и работать над ними в любом порядке. Например, написать скрипт и сразу посмотреть, как он работает. Остальные фрагменты кода при этом запускать не нужно, результат появляется тут же, под частью кода.

```$ jupyter notebook```


<!-- ![colab image](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Google_Colaboratory_SVG_Logo.svg/2560px-Google_Colaboratory_SVG_Logo.svg.png width="100") -->

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Google_Colaboratory_SVG_Logo.svg/2560px-Google_Colaboratory_SVG_Logo.svg.png" alt="numpy image" width="200"/>

**Google colab** - это облачный сервис от Google, который позволяет писать и выполнять Python-код в браузере без установки дополнительных программ.

Главные преимущества:

https://colab.research.google.com/rch.google.com/

## Библиотеки

<!-- ![numpy image](https://numpy.org/images/logo.svg) -->
<img src="https://numpy.org/images/logo.svg" alt="numpy image" width="100"/>

**NumPy** это open-source модуль для python, который предоставляет общие математические и числовые операции в виде пре-скомпилированных, быстрых функций. Они объединяются в высокоуровневые пакеты. Они обеспечивают функционал, который можно сравнить с функционалом MatLab. NumPy (Numeric Python) предоставляет базовые методы для манипуляции с большими массивами и матрицами.

*Входит в дистрибутив Anaconda*

<!-- ![pandas image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKPePf0eI9lrP20Ym-P0v-_B2yB6IHRoQiWw&s) -->
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKPePf0eI9lrP20Ym-P0v-_B2yB6IHRoQiWw&s" alt="pandas image" width="200"/>

**Pandas** — программная библиотека на языке Python для обработки и анализа данных. Работа pandas с данными строится поверх библиотеки NumPy, являющейся инструментом более низкого уровня. Предоставляет специальные структуры данных и операции для манипулирования числовыми таблицами и временны́ми рядами. Название библиотеки происходит от эконометрического термина «панельные данные», используемого для описания многомерных структурированных наборов информации.

*Входит в дистрибутив Anaconda*

![sklearn image](https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png)

**Scikit-learn** — библиотека, предназначенная для машинного обучения, написанная на языке программирования Python и распространяемая в виде свободного программного обеспечения.

В её состав входят различные алгоритмы, в том числе предназначенные для задач классификации, регрессионного и кластерного анализа данных, включая метод опорных векторов, метод случайного леса, алгоритм усиления градиента, метод k-средних и DBSCAN. Библиотека была разработана для взаимодействия с численными и научными библиотеками языка программирования Python NumPy и SciPy.

*Входит в дистрибутив Anaconda*

<!-- ![pytorch image](https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png) -->
<img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" alt="pytorch image" width="200"/>

**PyTorch** — фреймворк машинного обучения для языка Python с открытым исходным кодом, созданный на базе Torch. Используется для решения различных задач: компьютерное зрение, обработка естественного языка и т.д. Разрабатывается преимущественно группой искусственного интеллекта Facebook.

```conda install pytorch::pytorch```

<!-- ![matplotlib image](https://matplotlib.org/_static/logo_light.svg) -->
<img src="https://matplotlib.org/_static/logo_light.svg" alt="matplotlib image" width="200"/>

**Matplotlib** — библиотека на языке программирования Python для визуализации данных двумерной и трёхмерной графикой. Получаемые изображения могут быть использованы в качестве иллюстраций в публикациях.

*Входит в дистрибутив Anaconda*

<img src="https://upload.wikimedia.org/wikipedia/commons/8/8a/Plotly-logo.png" alt="plotly image" width="200"/>

**Plotly** — библиотека для визуализации данных. Plotly позволяет строить интерактивные визуализации. С помощью Plotly можно как изучать какие-то данные «на лету» (не перестраивая график в matplotlib, изменяя масштаб, включая/выключая какие-то данные), так и построить полноценный интерактивный отчёт (дашборд).

*Входит в дистрибутив Anaconda*

## Данные

Импортируем библиотеку. Pandas обычно импортируется как `pd`:

In [1]:
import pandas as pd

#### Pandas Series

Одной из основных структур данных в библиотеке Pandas является Pandas Series. Элемент Pandas Series похож на столбец в таблице: это одномерный массив, содержащий данные любого типа.

Элементы Pandas Series помечаются номерами индексов. Первое значение имеет индекс 0, второе - индекс 1 и т. д.

Заведем столбец Series из обычного питоновского массива:

In [30]:
a = [1, 7, 2]
series = pd.Series(a)
series

0    1
1    7
2    2
dtype: int64

Доступ к элементам

In [31]:
print(series.loc[0])
print(series.iloc[0])
print(series.shape)

1
1
(3,)

In [32]:
series = pd.Series(a, index = ["x", "y", "z"])

In [34]:
print(series.loc["y"])
print(series.iloc[1])
print(series.shape)

7
7
(3,)

Срез

In [36]:
series.iloc[1:]

y    7
z    2
dtype: int64

In [40]:
series.loc["y":]

y    7
z    2
dtype: int64

#### Pandas DataFrame

Столбец — это хорошо, но мы чаще работаем с целыми таблицами данных (наборами столбцов). Тип данных, соответствующий таблице — DataFrame.

Pandas DataFrame - это двумерная структура данных, подобная двумерному массиву или таблице со строками и столбцами. Иными словами, Pandas Series - это один столбец таблицы, а DataFrame - это вся таблица.

In [41]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

# можно создать таблицу из Python Dict
# keys словаря будут названиями столбцов
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

Доступ к отдельному столбцу таблицы можно получить по названию этого столбца:

In [42]:
df['calories']

0    420
1    380
2    390
Name: calories, dtype: int64

Доступ к строке таблицы также осуществляется с помощью .loc и .iloc:

In [43]:
print(df.iloc[1])
print(df.loc[1])

calories    380
duration     40
Name: 1, dtype: int64
calories    380
duration     40
Name: 1, dtype: int64

#### Создание таблицы Pandas DataFrame из файла

Скачаем два файла в формате .csv и создадим из них таблицы DataFrame

In [4]:
!gdown 17YX6P0YMTx12oNVPcuwGAQgKLOkA5Efy
!gdown 17_utMiYF01v1eDJeqkua8JNDzlQ6_pBe

Downloading...
From: https://drive.google.com/uc?id=17YX6P0YMTx12oNVPcuwGAQgKLOkA5Efy
To: /content/turbohackathon_task2_df2.csv
100% 64.7k/64.7k [00:00<00:00, 74.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=17_utMiYF01v1eDJeqkua8JNDzlQ6_pBe
To: /content/turbohackathon_task2_df1.csv
100% 555k/555k [00:00<00:00, 88.5MB/s]

In [8]:
df1 = pd.read_csv('./turbohackathon_task2_df1.csv')
df2 = pd.read_csv('./turbohackathon_task2_df2.csv')

В файлах представлены данные с ТЭЦ.  
Певый файл содержит данные о почасовых значения выработки электрической/тепловой энергии и расхода топлива.  
Второй файл содержит посуточную информацию о состоянии основного и вспомогательного оборудования.

Метод `.head()` позволяет вывести первые несколько строк таблицы в красивом формате.

In [9]:
df1.head()

,data,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
0,2023-01-01 00:00:00.000,0.0,53088.0,47988.0,98208.0,0.0,199284.0,93.67,169
1,2023-01-01 01:00:00.000,0.0,53088.0,48012.0,98192.0,0.0,199292.0,93.72,167
2,2023-01-01 01:59:59.990,0.0,53097.6,48024.0,98176.0,0.0,199297.6,93.79,165
3,2023-01-01 02:59:59.985,0.0,53068.8,47832.0,96992.0,0.0,197892.8,92.62,156
4,2023-01-01 03:59:59.980,0.0,53088.0,47772.0,96320.0,0.0,197180.0,92.23,151

In [44]:
df2.head(7)

,date,TG4,TG5,TG6,TG9,TG10,SB4,SB5,SB6,SB8,...,tower_5a,tower_5b,tower_6a,tower_6b,tower_7a,tower_7b,Ifwp_kWhrton,tamb,WB,Gfw
0,2023-01-01,0,1,1,1,0,0,0,1,1,...,1,1,1,1,0,0,7.35,-6.4,0,1124.625000
1,2023-01-02,0,1,1,1,0,0,0,1,1,...,1,1,1,1,0,0,7.38,-2.6,0,1112.958333
2,2023-01-03,0,1,1,1,0,0,2,2,1,...,1,1,1,1,0,0,7.63,-1.7,0,1101.333333
3,2023-01-04,0,1,1,1,0,0,1,0,1,...,1,1,1,1,0,0,7.34,-3.5,0,1109.875000
4,2023-01-05,0,1,1,1,0,0,1,0,1,...,1,1,1,1,0,0,7.24,-11.9,0,1154.833333
5,2023-01-06,0,1,1,1,0,0,1,0,1,...,1,1,1,1,0,0,7.26,-7.0,0,1170.333333
6,2023-01-07,0,1,1,1,0,0,2,2,1,...,1,1,1,1,0,0,8.11,-24.6,2,1210.958333

In [140]:
df1 = pd.read_csv(
    './turbohackathon_task2_df1.csv',
    parse_dates=["data"],
    index_col="data",)

df2 = pd.read_csv(
    './turbohackathon_task2_df2.csv',
    parse_dates=["date"],
    index_col="date",)

In [76]:
df1.index

DatetimeIndex([       '2023-01-01 00:00:00',        '2023-01-01 01:00:00',
               '2023-01-01 01:59:59.990000', '2023-01-01 02:59:59.985000',
               '2023-01-01 03:59:59.980000', '2023-01-01 04:59:59.975000',
               '2023-01-01 05:59:59.970000', '2023-01-01 06:59:59.965000',
               '2023-01-01 07:59:59.960000', '2023-01-01 08:59:59.955000',
               ...
                      '2023-12-31 14:00:00',        '2023-12-31 15:00:00',
                      '2023-12-31 16:00:00',        '2023-12-31 17:00:00',
                      '2023-12-31 18:00:00',        '2023-12-31 19:00:00',
                      '2023-12-31 20:00:00',        '2023-12-31 21:00:00',
                      '2023-12-31 22:00:00',        '2023-12-31 23:00:00'],
              dtype='datetime64[ns]', name='data', length=7344, freq=None)

Метод `.sample()` позволяет вывести рандомные строки.  
Метод `.tail()` - последние.

In [63]:
df1.sample(3)

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-11-11 06:00:00.000,0.0,60768.0,0.0,66960.0,50870.4,178598.4,183.15,105
2023-04-26 13:00:00.000,0.0,60979.2,54084.0,93920.0,0.0,208983.2,88.37,23
2023-06-01 21:00:00.000,62841.6,0.0,0.0,84144.0,40176.0,187161.6,78.10,0

In [78]:
df2.tail()

,TG4,TG5,TG6,TG9,TG10,SB4,SB5,SB6,SB8,SB9,...,tower_5a,tower_5b,tower_6a,tower_6b,tower_7a,tower_7b,Ifwp_kWhrton,tamb,WB,Gfw
date,,,,,,,,,,,,,,,,,,,,,
2023-12-27,1,0,1,1,0,1,1,1,1,0,...,1,1,0,0,1,1,6.98,-1.6,0,1202.333333
2023-12-28,1,0,1,1,0,1,1,1,1,0,...,1,1,2,2,2,2,7.01,-1.3,0,1180.416667
2023-12-29,1,0,1,1,0,1,2,1,1,0,...,1,1,1,1,0,0,7.25,-6.5,0,1210.708333
2023-12-30,1,0,2,1,2,1,0,1,1,0,...,1,1,1,1,0,0,7.52,-5.3,0,1206.958333
2023-12-31,1,0,0,1,1,1,0,1,1,0,...,1,1,1,1,0,0,7.43,-0.4,0,1185.958333

С помощью методов .loc и .iloc можно посмотреть отдельную строку или строки.

In [83]:
df1.loc["2023-09-01 21:00:00"]

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-09-01 21:00:00,0.0,50832.0,44568.0,89696.0,0.0,185096.0,77.28,18

In [85]:
df1.loc["2023-09-01 00:00:00":"2023-09-01 06:00:00"]

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-09-01 00:00:00,0.0,47961.6,43404.0,82912.0,0.0,174277.6,74.21,19
2023-09-01 01:00:00,0.0,47980.8,43404.0,82880.0,0.0,174264.8,74.19,19
2023-09-01 02:00:00,0.0,47961.6,41520.0,84928.0,0.0,174409.6,73.82,18
2023-09-01 03:00:00,0.0,47971.2,41244.0,85264.0,0.0,174479.2,73.64,18
2023-09-01 04:00:00,0.0,47961.6,41388.0,85264.0,0.0,174613.6,73.58,18
2023-09-01 05:00:00,0.0,47961.6,41256.0,85264.0,0.0,174481.6,73.46,16
2023-09-01 06:00:00,0.0,52636.8,41184.0,92128.0,0.0,185948.8,76.96,17

In [87]:
df1.iloc[100:103]

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-01-05 04:00:00.000,0.0,53472.0,45660.0,95216.0,0.0,194348.0,90.19,156
2023-01-05 05:00:00.000,0.0,53481.6,47160.0,94064.0,0.0,194705.6,90.92,156
2023-01-05 06:00:00.985,0.0,53971.2,46764.0,93632.0,0.0,194367.2,91.29,157

In [92]:
df1.loc[["2023-09-01 00:00:00", "2023-10-01 00:00:00", "2023-11-01 00:00:00"]]

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-09-01,0.0,47961.6,43404.0,82912.0,0.0,174277.6,74.21,19
2023-10-01,32294.4,56956.8,0.0,0.0,50064.0,139315.2,65.35,16
2023-11-01,40963.2,59222.4,0.0,6320.0,56304.0,162809.6,86.46,111

Доступ к колонке

In [94]:
df1.columns

Index(['TG4_kWhr', 'TG5_kWhr', 'TG6_kWhr', 'TG9_kWhr', 'TG10_kWhr', 'sum_kWhr',
       'B_1e3m3', 'Q_gcalhr'],
      dtype='object')

In [95]:
df1["sum_kWhr"]

data
2023-01-01 00:00:00.000    199284.0
2023-01-01 01:00:00.000    199292.0
2023-01-01 01:59:59.990    199297.6
2023-01-01 02:59:59.985    197892.8
2023-01-01 03:59:59.980    197180.0
                             ...
2023-12-31 19:00:00.000    203692.8
2023-12-31 20:00:00.000    199212.8
2023-12-31 21:00:00.000    198953.6
2023-12-31 22:00:00.000    198819.2
2023-12-31 23:00:00.000    198934.4
Name: sum_kWhr, Length: 7344, dtype: float64

In [99]:
df1.loc["2023-09-01 00:00:00", "sum_kWhr"]

data
2023-09-01    174277.6
Name: sum_kWhr, dtype: float64

In [101]:
df1.loc["2023-09-01 00:00:00":"2023-09-01 04:00:00", ["sum_kWhr", "Q_gcalhr"]]

                     sum_kWhr  Q_gcalhr
data
2023-09-01 00:00:00  174277.6        19
2023-09-01 01:00:00  174264.8        19
2023-09-01 02:00:00  174409.6        18
2023-09-01 03:00:00  174479.2        18
2023-09-01 04:00:00  174613.6        18

In [105]:
df1.iloc[400:405, 1:3]

                     TG5_kWhr  TG6_kWhr
data
2023-01-17 16:00:00   59126.4   56124.0
2023-01-17 17:00:00   59116.8   55800.0
2023-01-17 18:00:00   59126.4   55764.0
2023-01-17 19:00:00   59750.4   55848.0
2023-01-17 20:00:00   61142.4   55632.0

Фильтрация строк

In [106]:
df2.columns

Index(['TG4', 'TG5', 'TG6', 'TG9', 'TG10', 'SB4', 'SB5', 'SB6', 'SB8', 'SB9',
       'SB10', 'OB1A', 'OB1B', 'OB2A', 'OB2B', 'OB3A', 'OB3B', 'SPG1', 'SPG2',
       'PB1', 'PB2', 'PSV_degC', 'OSV_degC', 'Gsv_ton', 's10ata_Gcalhr',
       's10ata_tonhr', 's16ata_Gcalhr', 's16ata_tonhr', 's30ata_Gcalhr',
       's30ata_tonhr', 'sum_fw_ton', 'sum_min_MW', 'sum_max_MW', 'FWP5',
       'FWP6', 'FWP7', 'FWP8', 'FWP9', 'FWP10', 'FWP11', 'FWP12', 'SEN1',
       'SEN2', 'SEN3', 'SEN4', 'SEN5', 'SEN6', 'SEN7', 'SEN1I', 'SEN2I',
       'SEN3I', 'SEN1II', 'SEN2II', 'SEN3II', 'SEN4II', 'CN3a', 'CN3b', 'CN4a',
       'CN4b', 'CN5a', 'CN5b', 'CN9a', 'CN9b', 'tower_5a', 'tower_5b',
       'tower_6a', 'tower_6b', 'tower_7a', 'tower_7b', 'Ifwp_kWhrton', 'tamb',
       'WB', 'Gfw'],
      dtype='object')

In [110]:
df2[df2["TG6"] == 0].head()

,TG4,TG5,TG6,TG9,TG10,SB4,SB5,SB6,SB8,SB9,...,tower_5a,tower_5b,tower_6a,tower_6b,tower_7a,tower_7b,Ifwp_kWhrton,tamb,WB,Gfw
date,,,,,,,,,,,,,,,,,,,,,
2023-03-01,1,1,0,1,0,0,1,1,1,0,...,1,1,1,1,0,0,6.66,-3.8,0,1163.583333
2023-03-02,1,1,0,1,0,0,1,1,1,0,...,1,1,1,1,0,0,6.68,-6.3,0,1188.333333
2023-03-03,1,1,0,1,0,0,1,1,1,0,...,1,1,1,1,0,0,6.66,-5.7,0,1193.458333
2023-03-04,1,1,0,1,0,0,1,1,1,0,...,1,1,1,1,0,0,6.65,-1.4,0,1203.583333
2023-03-05,1,1,0,1,0,0,1,1,1,0,...,1,1,1,1,0,0,6.67,-0.4,0,1154.875000

In [114]:
df2[(df2["tamb"] > 20) & (df2["TG6"] == 0)]

,TG4,TG5,TG6,TG9,TG10,SB4,SB5,SB6,SB8,SB9,...,tower_5a,tower_5b,tower_6a,tower_6b,tower_7a,tower_7b,Ifwp_kWhrton,tamb,WB,Gfw
date,,,,,,,,,,,,,,,,,,,,,
2023-05-28,1,0,0,1,1,1,0,1,1,1,...,1,1,1,1,1,1,7.58,25.9,0,1047.125000
2023-05-29,1,0,0,1,1,1,0,1,1,1,...,1,1,1,1,1,1,7.75,25.7,0,997.875000
2023-05-30,1,0,0,1,1,1,0,1,1,1,...,1,1,1,1,1,1,7.77,25.4,0,973.750000
2023-05-31,1,0,0,1,1,1,0,1,1,1,...,1,1,1,1,1,1,7.70,26.0,0,1015.833333
2023-06-01,1,0,0,1,1,1,0,1,1,1,...,1,1,1,1,1,1,7.70,27.7,0,982.916667

& соответствует "и", | соответствует "или"

Также, получая доступ к элементу с помощью .loc(), можно обновить значение этого элемента в таблице. Пересчитаем Гкал/ч тепловой нагруки в МВт

Вот как сейчас выглядят наши данные:

In [116]:
df1.columns

Index(['TG4_kWhr', 'TG5_kWhr', 'TG6_kWhr', 'TG9_kWhr', 'TG10_kWhr', 'sum_kWhr',
       'B_1e3m3', 'Q_gcalhr'],
      dtype='object')

In [141]:
df1.head()

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-01-01 00:00:00.000,0.0,53088.0,47988.0,98208.0,0.0,199284.0,93.67,169
2023-01-01 01:00:00.000,0.0,53088.0,48012.0,98192.0,0.0,199292.0,93.72,167
2023-01-01 01:59:59.990,0.0,53097.6,48024.0,98176.0,0.0,199297.6,93.79,165
2023-01-01 02:59:59.985,0.0,53068.8,47832.0,96992.0,0.0,197892.8,92.62,156
2023-01-01 03:59:59.980,0.0,53088.0,47772.0,96320.0,0.0,197180.0,92.23,151

In [143]:
df1.loc[:, ["Q_gcalhr"]] = round(df1.loc[:, ["Q_gcalhr"]] * 4.184/3.6).astype("Int64")

In [144]:
df1.head()

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
data,,,,,,,,
2023-01-01 00:00:00.000,0.0,53088.0,47988.0,98208.0,0.0,199284.0,93.67,196
2023-01-01 01:00:00.000,0.0,53088.0,48012.0,98192.0,0.0,199292.0,93.72,194
2023-01-01 01:59:59.990,0.0,53097.6,48024.0,98176.0,0.0,199297.6,93.79,192
2023-01-01 02:59:59.985,0.0,53068.8,47832.0,96992.0,0.0,197892.8,92.62,181
2023-01-01 03:59:59.980,0.0,53088.0,47772.0,96320.0,0.0,197180.0,92.23,175

In [145]:
df2.columns

Index(['TG4', 'TG5', 'TG6', 'TG9', 'TG10', 'SB4', 'SB5', 'SB6', 'SB8', 'SB9',
       'SB10', 'OB1A', 'OB1B', 'OB2A', 'OB2B', 'OB3A', 'OB3B', 'SPG1', 'SPG2',
       'PB1', 'PB2', 'PSV_degC', 'OSV_degC', 'Gsv_ton', 's10ata_Gcalhr',
       's10ata_tonhr', 's16ata_Gcalhr', 's16ata_tonhr', 's30ata_Gcalhr',
       's30ata_tonhr', 'sum_fw_ton', 'sum_min_MW', 'sum_max_MW', 'FWP5',
       'FWP6', 'FWP7', 'FWP8', 'FWP9', 'FWP10', 'FWP11', 'FWP12', 'SEN1',
       'SEN2', 'SEN3', 'SEN4', 'SEN5', 'SEN6', 'SEN7', 'SEN1I', 'SEN2I',
       'SEN3I', 'SEN1II', 'SEN2II', 'SEN3II', 'SEN4II', 'CN3a', 'CN3b', 'CN4a',
       'CN4b', 'CN5a', 'CN5b', 'CN9a', 'CN9b', 'tower_5a', 'tower_5b',
       'tower_6a', 'tower_6b', 'tower_7a', 'tower_7b', 'Ifwp_kWhrton', 'tamb',
       'WB', 'Gfw'],
      dtype='object')

In [161]:
df2.loc[:, ["TG9"]].value_counts()

TG9
 1     228
 0      47
-2       1
Name: count, dtype: int64

In [159]:
df2.loc[df2["TG9"] == 2, ["TG9"]] = -2
df2.loc[:, ["TG9"]].value_counts()

TG9
 1     228
 0      47
-2       1
Name: count, dtype: int64

In [162]:
df2.loc[df2["TG9"] == 2, ["TG9"]] = 2

Далее, у объекта DataFrame есть удобные методы для получения общей информации о данных.

Метод `.info()` сообщает нам, сколько в наших данных строк и столбцов, и для каждого столбца дает его название, тип данных в нем и количество непустых значений в нем:

In [163]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7344 entries, 2023-01-01 00:00:00 to 2023-12-31 23:00:00
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TG4_kWhr   7344 non-null   float64
 1   TG5_kWhr   7344 non-null   float64
 2   TG6_kWhr   7344 non-null   float64
 3   TG9_kWhr   7344 non-null   float64
 4   TG10_kWhr  7344 non-null   float64
 5   sum_kWhr   7344 non-null   float64
 6   B_1e3m3    7344 non-null   float64
 7   Q_gcalhr   7344 non-null   int64
dtypes: float64(7), int64(1)
memory usage: 516.4 KB

Еще один метод описания данных — `.describe()`. Он выводит основные статистики числовых столбцов данных:

In [50]:
df1.describe()

,TG4_kWhr,TG5_kWhr,TG6_kWhr,TG9_kWhr,TG10_kWhr,sum_kWhr,B_1e3m3,Q_gcalhr
count,7344.000000,7344.000000,7344.000000,7344.000000,7344.000000,7344.000000,7344.000000,7344.000000
mean,28543.594336,43820.713725,36625.872222,70955.934423,12509.660444,192455.775150,88.211153,82.189542
std,27456.926540,24187.001279,23243.026165,33943.308631,21895.967583,29868.073605,18.222681,67.705185
min,0.000000,0.000000,0.000000,0.000000,0.000000,135513.600000,54.250000,-5.000000
25%,0.000000,42568.800000,0.000000,58096.000000,0.000000,169023.800000,77.127500,17.000000
50%,31857.600000,54604.800000,48810.000000,84528.000000,0.000000,190912.800000,84.425000,93.000000
75%,56880.000000,61046.400000,54852.000000,97184.000000,20695.200000,210119.400000,95.232500,126.000000
max,70348.800000,87129.600000,63705.600000,108800.000000,60297.600000,296175.200000,194.440000,240.000000

## Анализ данных